### ISSUE TITLE
[ERROR] message：Call to undefined method W7\Core\Config\Config::get()

### ISSUE THREAD

**Issue by bencen** [we7coreteam/w7-rangine-project-document#7]
[ERROR] message：Call to undefined method W7\Core\Config\Config::get()                                                 
         file：/www/wwwroot/rw.xx.cn/vendor/w7/rangine-http-message/src/ServiceProvider.php                        
         line：29

**Comment by bencen** [comment]
https://github.com/we7coreteam/w7-rangine-project-document/releases/ 
从这个版下的报这个错，后面直接升到"w7/rangine": "2.3.4",才没问题，也没有install.html文件啊。

**Comment by titrxw** [comment]
已处理，更新版本到v1.0.4
