### ISSUE TITLE
1.1.3版本安装完成后前端markdown没有样式

### ISSUE THREAD

**Issue by nowbe** [we7coreteam/w7-rangine-project-document#8]
前端的VUE生成的js中有报错，导致markdown输出的前台页面，没有html解析的样式，依然呈现markdown格式。

**Comment by 563384868** [comment]
> 前端的VUE生成的js中有报错，导致markdown输出的前台页面，没有html解析的样式，依然呈现markdown格式。

前端代码已更新，重新拉取代码

**Comment by nowbe** [comment]
能否将vue模板的部分也开源一些。这样子方便修改一下样式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "we7coreteam/w7-rangine-project-document"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月21日(星期五) 下午2:08
收件人:&nbsp;"we7coreteam/w7-rangine-project-document"<w7-rangine-project-document@noreply.github.com&gt;;
抄送:&nbsp;"nowbe"<nowbe@wolike.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [we7coreteam/w7-rangine-project-document] 1.1.3版本安装完成后前端markdown没有样式 (#8)





  
前端的VUE生成的js中有报错，导致markdown输出的前台页面，没有html解析的样式，依然呈现markdown格式。
  
前端代码已更新，重新拉取代码

**Comment by donknap** [comment]
https://github.com/we7coreteam/w7-rangine-project-document-ued 已经开放到github上了
